%% Graficar funciones de activacion de la RNA
% RNA: 11-32-16-8-4
% Capas ocultas: tansig
% Capa de salida: softmax

clear;
clc;
close all;

%% Configuracion general
z = linspace(-6,6,1000);

% Funcion tansig usada por MATLAB:
% tansig(z) = 2/(1 + exp(-2z)) - 1
yTansig = 2 ./ (1 + exp(-2*z)) - 1;

%% Representacion de softmax para cuatro clases
% Se varia la activacion de la clase 1.
% Las activaciones de las clases 2, 3 y 4 se fijan en cero.
logits = [z; ...
          zeros(size(z)); ...
          zeros(size(z)); ...
          zeros(size(z))];

% Implementacion numericamente estable de softmax
logitsEstables = logits - max(logits,[],1);
expLogits = exp(logitsEstables);
probabilidades = expLogits ./ sum(expLogits,1);

%% Crear figura
fig = figure( ...
    'Color','w', ...
    'Units','centimeters', ...
    'Position',[2 2 17 7.5]);

t = tiledlayout(fig,1,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');

%% Panel a: tansig
ax1 = nexttile(t,1);

plot(ax1,z,yTansig, ...
    'Color',[0.10 0.35 0.75], ...
    'LineWidth',2.2);

hold(ax1,'on');
yline(ax1,0,'--', ...
    'Color',[0.35 0.35 0.35], ...
    'LineWidth',0.8);
xline(ax1,0,'--', ...
    'Color',[0.35 0.35 0.35], ...
    'LineWidth',0.8);

xlabel(ax1,'Entrada, $z$', ...
    'Interpreter','latex');
ylabel(ax1,'$f_{\mathrm{tansig}}(z)$', ...
    'Interpreter','latex');

title(ax1,'(a) Función \texttt{tansig}', ...
    'Interpreter','latex', ...
    'FontWeight','normal');

xlim(ax1,[-6 6]);
ylim(ax1,[-1.1 1.1]);
xticks(ax1,-6:2:6);
yticks(ax1,-1:0.5:1);

grid(ax1,'on');
box(ax1,'on');

%% Panel b: softmax
ax2 = nexttile(t,2);

colores = [ ...
    0.80 0.15 0.15
    0.10 0.55 0.25
    0.55 0.25 0.70
    0.90 0.55 0.10];

hold(ax2,'on');

for c = 1:4
    plot(ax2,z,probabilidades(c,:), ...
        'Color',colores(c,:), ...
        'LineWidth',2.0);
end

yline(ax2,0.25,':', ...
    'Color',[0.30 0.30 0.30], ...
    'LineWidth',1.0);

xlabel(ax2,'Activación de la clase 1, $z_1$', ...
    'Interpreter','latex');
ylabel(ax2,'Probabilidad, $\widehat{p}_j$', ...
    'Interpreter','latex');

title(ax2,'(b) Función \textit{softmax}', ...
    'Interpreter','latex', ...
    'FontWeight','normal');

legend(ax2, ...
    {'Clase 1','Clase 2','Clase 3','Clase 4'}, ...
    'Location','eastoutside', ...
    'Interpreter','latex', ...
    'FontSize',8);

xlim(ax2,[-6 6]);
ylim(ax2,[0 1.05]);
xticks(ax2,-6:2:6);
yticks(ax2,0:0.2:1);

grid(ax2,'on');
box(ax2,'on');

%% Formato comun
set([ax1 ax2], ...
    'FontName','Times New Roman', ...
    'FontSize',9, ...
    'LineWidth',0.8, ...
    'TickLabelInterpreter','latex', ...
    'GridAlpha',0.16, ...
    'MinorGridAlpha',0.08);

%% Exportacion
exportgraphics(fig, ...
    'funciones_activacion_RNA.pdf', ...
    'ContentType','vector');

exportgraphics(fig, ...
    'funciones_activacion_RNA.png', ...
    'Resolution',600);

disp('Archivos generados:');
disp('  funciones_activacion_RNA.pdf');
disp('  funciones_activacion_RNA.png');